sude: required
services:
  - docker

before_install:
  - docker build -t ylihemmo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ylihemmo/react-test npm test -- --coverage

after_success:
  - docker build -t ylihemmo/multi-client ./client
  - docker build -t ylihemmo/multi-nginx ./nginx
  - docker build -t ylihemmo/multi-server ./server
  - docker build -t ylihemmo/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ylihemmo/multi-client
  - docker push ylihemmo/multi-nginx
  - docker push ylihemmo/multi-server
  - docker push ylihemmo/multi-worker
